name: Build Android APK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hxvlc
          haxelib install tjson
          haxelib install SScript
          haxelib install flxanimate
          haxelib git linc_luajit github.com
          haxelib git extension-androidtools github.com
          haxelib run lime setup android
          
      - name: Configure Android
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Build APK
        run: haxelib run lime build android -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MADNESS-Android-APK
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          
