name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Install Android Components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;21.4.7075529"
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Base Libs
        run: |
         haxelib setup ~/haxelib
         haxelib install lime 8.1.2 --quiet
         haxelib install openfl 9.3.3 --quiet
         haxelib install flixel 5.5.0 --quiet
         haxelib install flixel-addons 3.2.2 --quiet
         haxelib install flixel-ui 2.5.0 --quiet
         haxelib install hxcpp 4.3.2 --quiet
         haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc.git --quiet
         haxelib run lime rebuild hxcpp
      - name: Install Project Libs
        run: |
          sudo apt-get install -y libxml2-utils
          PROJECT_FILE=$(find . -maxdepth 2 -iname "project.xml" -print -quit)
          if [ -z "$PROJECT_FILE" ]; then
            echo "ERRO: Project.xml n√£o encontrado!"
            exit 1
          fi
          LIBS=$(xmllint --xpath '//haxelib/@name' "$PROJECT_FILE" | sed 's/name=//g' | tr -d '"')
          for lib in $LIBS; do
            if [[ "$lib" != "lime" && "$lib" != "hxcpp" ]]; then
              haxelib install $lib --quiet || echo "Aviso: falha em $lib"
            fi
          done

      - name: Configure and Build
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime setup android -y
          PROJECT_DIR=$(dirname $(find . -maxdepth 2 -iname "project.xml" -print -quit))
          cd $PROJECT_DIR
          haxelib run lime build android -release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Madness-Android-APK
          path: ./**/export/release/android/bin/app/build/outputs/apk/release/*.apk
