name: Build Android
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          # Correção para erro de permissão do Git em 2026
          git config --global safe.directory '*'
          
          haxelib setup ~/haxelib
          haxelib install lime 8.1.2 --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.6.2 --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install tjson --quiet
          haxelib install SScript --quiet
          haxelib install flxanimate --quiet
          haxelib install hxcpp --quiet
          
          # Instalando com links diretos e estáveis
          haxelib git hxvlc github.com --quiet
          haxelib git linc_luajit github.com --quiet
          haxelib git extension-androidtools github.com --quiet
          haxelib git hxCodec github.com --quiet
          haxelib git hxdiscord_rpc github.com --quiet

      - name: Configure Lime Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime setup android -y

      - name: Build APK
        run: haxelib run lime build android -release

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: MADNESS-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          
