name: Build Android
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib install SScript 5.2.0 --quiet
          haxelib install flxanimate 1.2.0 --quiet

          # Links completos para evitar o erro de 'repositório não existe'
          git clone github.com ~/haxelib/linc_luajit/git
          haxelib dev linc_luajit ~/haxelib/linc_luajit/git
          
          git clone github.com ~/haxelib/extension-androidtools/git
          haxelib dev extension-androidtools ~/haxelib/extension-androidtools/git

          git clone github.com ~/haxelib/hxCodec/git
          haxelib dev hxCodec ~/haxelib/hxCodec/git

      - name: Configure Lime Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_11_X64
          haxelib run lime setup android -y

      - name: Build APK
        run: haxelib run lime build android -release

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: MADNESS-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
